v2.0.6 window object timeout
Summary:
User report JS confliect issue in Magento 2

On the Magento 2 checkout page, this caused JavaScript conflicts and instability. In GTM Preview, some Meta Pixel tags were stuck in a Still running state.

We also observed logs like:

ParamBuilder script loaded successfully, processing and collecting all params...
ERROR: clientParamBuilder wasn't loaded correctly.

The clientParamBuilder object was not available on window in the checkout page.

https://github.com/facebook/GoogleTagManager-WebTemplate-For-FacebookPixel/issues/31

___

overriding_review_checks_triggers_an_audit_and_retroactive_review
Oncall Short Name: sae_partnerships

Differential Revision: D105516871

fbshipit-source-id: ef1420b523e4a8a995f61bc183559ab453d40427