window object timeout
Summary:
User report JS confliect issue in Magento 2

On the Magento 2 checkout page, this caused JavaScript conflicts and instability. In GTM Preview, some Meta Pixel tags were stuck in a Still running state.

We also observed logs like:

ParamBuilder script loaded successfully, processing and collecting all params...
ERROR: clientParamBuilder wasn't loaded correctly.

The clientParamBuilder object was not available on window in the checkout page.

https://github.com/facebook/GoogleTagManager-WebTemplate-For-FacebookPixel/issues/31

Differential Revision: D103720578

fbshipit-source-id: ab90c12f3ff6e61adc3fc590fd6b70646db3dbd0